Работа выполнена.
avalon-dev-j30/lab-2-ustinovsa pull request #1
Opened 2019-05-26 20:50 UTC by ustinovsa

@konivex 
Доброго времени суток!
Прошу проверить работу.

2019-06-02 13:04 UTC, konivex requested changes
Исправьте замечания.

2019-06-02 13:04 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
Этот конструктор инициализирует объект текущей записью из ResulSet'а.
Метод convert должен создавать коллекцию продуктов, используя этот конструктор.

2019-06-02 13:04 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +            String updateQuery = "UPDATE APP.product_code"
Ни в одном месте вашего класса нет кода, в котором бы присутствовали старый и новый код продукта одновременно, так что в части SET SQL-оператора UPDATE установка значения поля prod_code бессмысленна.

2019-06-02 15:40 UTC, ustinovsa commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +            String updateQuery = "UPDATE APP.product_code"
@konivex 
Замечания исправлены

2019-06-02 20:58 UTC, konivex requested changes
Исправьте замечание.

2019-06-02 20:58 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
Замечание всё ещё актуально.

2019-06-03 06:19 UTC, ustinovsa commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
Сегодня залью, не то запушил. там в convert вместо ручной инициализации и создания конструктором просто используется данный метод.

2019-06-04 19:19 UTC, ustinovsa reviewed
@konivex  ниже актуальный файл, там корректно, мне кажется

2019-06-04 19:19 UTC, ustinovsa commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +                productList.add(new ProductCode(set));
@konivex вроде бы так, если я все правильно понял

2019-06-04 20:10 UTC, konivex requested changes
Замечание пока в силе. Исправляйте.

2019-06-04 20:10 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
Замечание всё ещё актуально.
См. комментарий к методу convert.

2019-06-04 20:10 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
>          Collection<ProductCode> productList = new HashSet<>();
Ваша реализация для любой непустой таблицы всегда будет возвращать коллекцию из одного элемента.

2019-06-04 20:44 UTC, ustinovsa commented on src/ru/avalon/java/j30/labs/ProductCode.java
>          Collection<ProductCode> productList = new HashSet<>();
@konivex теперь точно исправил, для отладчика оставил коллекцию pcl

2019-06-04 20:58 UTC, konivex approved these changes
Зачтено.

2019-06-07 05:50 UTC, merged